enum COMMANDS{
	CMD_NOP = 0x0,
	CMD_WR_TO_INPUT_REG = 0x1,
	CMD_UPDATE_DAC_REG = 0x2,
	CMD_WR_UPDATE_DAC_REG = 0x3,
	CMD_WR_CTRL_REG = 0x4,
	CMD_NOP_ALT_1 = 0x5,
	CMD_NOP_ALT_2 = 0x6,
	CMD_SW_DATA_RESET = 0x7,
	CMD_RESERVED = 0x8,
	CMD_DIS_DAISY_CHAIN = 0x9,
	CMD_RD_INPUT_REG = 0xA,
	CMD_RD_DAC_REG = 0xB,
	CMD_RD_CTRL_REG = 0xC,
	CMD_NOP_ALT_3 = 0xD,
	CMD_NOP_ALT_4 = 0xE,
	CMD_SW_FULL_RESET = 0xF
};

enum CV{
	CV_ZERO = 0x0,
	CV_MID_SCALE = 0x1,
	CV_FULL_SCALE = 0x2
};

enum OVR{
	OVR_DISABLED = 0x0,
	OVR_ENABLED = 0x1
};

enum B2C{
	BINARY = 0x0,
	COMPLEMENT = 0x1,
};

enum ETS{
	TERMAL_ALERT_DISABLED = 0x0,
	TERMAL_ALERT_ENABLED = 0x1
};

enum IRO{
	IRO_DISABLED = 0x0,
	IRO_ENABLED = 0x1
};

enum PV{
	PV_ZERO = 0x0,
	PV_MID_SCALE = 0x1,
	PV_FULL_SCALE = 0x2
};

enum RA{
	RANGE_10_10 = 0x0,
	RANGE_0_10 = 0x1,
	RANGE_5_5 = 0x2,
	RANGE_0_5 = 0x3,
	RANGE_2_5_7_5 = 0x4,
	RANGE_3_3 = 0x5,
	RANGE_0_16 = 0x6,
	RANGE_0_20 = 0x7
};
